import type { Metadata } from "next";
import { Poppins as FontSans } from "next/font/google";
import '@xyflow/react/dist/style.css';
import "./globals.css";

const font = FontSans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} h-screen antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
